# Generated by Django 4.2.4 on 2023-09-22 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='institute',
            options={'verbose_name': 'Institute', 'verbose_name_plural': 'Institute'},
        ),
    ]
