# Generated by Django 4.2.4 on 2023-09-23 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0002_alter_institute_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institute',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
    ]
