# Generated by Django 4.2.4 on 2023-09-22 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor_summa', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sponsorsumma',
            options={'verbose_name': 'Sponsor summa', 'verbose_name_plural': 'Sponsor summa'},
        ),
    ]
