# Generated by Django 4.2.4 on 2023-09-23 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor', '0003_alter_sponsor_comment_alter_sponsor_firm_and_more'),
        ('student', '0003_alter_student_contract_alter_student_full_name_and_more'),
        ('sponsor_summa', '0002_alter_sponsorsumma_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsorsumma',
            name='sponsor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sponsor.sponsor', verbose_name='sponsor'),
        ),
        migrations.AlterField(
            model_name='sponsorsumma',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student', verbose_name='student'),
        ),
        migrations.AlterField(
            model_name='sponsorsumma',
            name='summa',
            field=models.BigIntegerField(verbose_name='summa'),
        ),
    ]
