# Generated by Django 4.2.4 on 2023-08-30 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0004_delete_institute'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('sum', models.BigIntegerField()),
                ('firm', models.CharField(max_length=255)),
                ('spent', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('get_status_display', models.CharField(max_length=255)),
                ('comment', models.TextField()),
                ('payment_type', models.ManyToManyField(to='base.paymenttype')),
            ],
        ),
    ]
