# Generated by Django 4.2.4 on 2023-09-11 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SponsorTariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summa', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('sum', models.BigIntegerField()),
                ('firm', models.CharField(max_length=255)),
                ('is_legal', models.BooleanField(blank=True, default=False, null=True)),
                ('spent', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('get_status_display', models.IntegerField(choices=[(1, 'Yangi'), (2, 'Modernarsiyada'), (3, 'Tasdiqlangan'), (4, 'Bekor qilingan')], default=1)),
                ('comment', models.TextField(blank=True, null=True)),
                ('payment_type', models.ManyToManyField(to='base.paymenttype')),
            ],
        ),
    ]
