# Generated by Django 4.2.4 on 2023-09-22 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sponsor',
            options={'verbose_name': 'Sponsor', 'verbose_name_plural': 'Sponsor'},
        ),
        migrations.AlterModelOptions(
            name='sponsortariff',
            options={'verbose_name': 'Sponsor tariff', 'verbose_name_plural': 'Sponsor tariff'},
        ),
    ]
