# Generated by Django 4.2.4 on 2023-08-30 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='get_status_display',
            field=models.CharField(default='Yangi', max_length=255),
        ),
    ]
