# Generated by Django 4.2.4 on 2023-09-23 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_faq_answer_alter_faq_question_and_more'),
        ('sponsor', '0002_alter_sponsor_options_alter_sponsortariff_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='comment'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='firm',
            field=models.CharField(max_length=255, verbose_name='Firma'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='full_name',
            field=models.CharField(max_length=255, verbose_name='full name'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='get_status_display',
            field=models.IntegerField(choices=[(1, 'Yangi'), (2, 'Modernarsiyada'), (3, 'Tasdiqlangan'), (4, 'Bekor qilingan')], default=1, verbose_name='display status'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='is_legal',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='is legal'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='payment_type',
            field=models.ManyToManyField(to='base.paymenttype', verbose_name='payment type'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='spent',
            field=models.BigIntegerField(verbose_name='spent'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='sum',
            field=models.BigIntegerField(verbose_name='summa'),
        ),
        migrations.AlterField(
            model_name='sponsortariff',
            name='summa',
            field=models.BigIntegerField(verbose_name='summa'),
        ),
    ]
