# Generated by Django 4.2.4 on 2023-08-30 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor', '0002_alter_sponsor_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='is_legal',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
