# Generated by Django 4.2.4 on 2023-08-30 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor', '0004_sponsorsumma'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SponsorSumma',
        ),
    ]
