# Generated by Django 4.2.4 on 2023-08-30 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor', '0005_delete_sponsorsumma'),
    ]

    operations = [
        migrations.CreateModel(
            name='SponsorTariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summa', models.BigIntegerField()),
            ],
        ),
    ]
