# Generated by Django 4.2.4 on 2023-09-09 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor', '0006_sponsortariff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='get_status_display',
            field=models.CharField(default=1, max_length=255),
        ),
    ]
