# Generated by Django 4.2.4 on 2023-09-09 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor', '0008_alter_sponsor_get_status_display'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='get_status_display',
            field=models.IntegerField(choices=[(1, 'Yangi'), (2, 'Modernarsiyada'), (3, 'Tasdiqlangan'), (4, 'Bekor qilingan')], default=1),
        ),
    ]
