# Generated by Django 4.2.4 on 2023-08-30 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_income', models.IntegerField()),
                ('need', models.IntegerField()),
                ('other', models.IntegerField()),
            ],
        ),
    ]
