# Generated by Django 4.2.4 on 2023-08-30 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_dashboard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard',
            name='need',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='other',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='total_income',
            field=models.BigIntegerField(),
        ),
    ]
