# Generated by Django 4.2.4 on 2023-08-30 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_dashboard_need_alter_dashboard_other_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Institute',
        ),
    ]
