# Generated by Django 4.2.4 on 2023-09-09 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_delete_institute'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dashboard',
        ),
    ]
