# Generated by Django 4.2.4 on 2023-09-11 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institute', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('type', models.IntegerField(choices=[(1, 'Bakalavr'), (2, 'Magistr'), (3, 'Phd')])),
                ('phone', models.CharField(max_length=255)),
                ('contract', models.BigIntegerField(blank=True, null=True)),
                ('given', models.BigIntegerField(blank=True, null=True)),
                ('get_status_display', models.IntegerField(choices=[(1, 'Yangi'), (2, 'Modernarsiyada'), (3, 'Tasdiqlangan'), (4, 'Bekor qilingan')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institute.institute')),
            ],
        ),
    ]
