# Generated by Django 4.2.4 on 2023-09-23 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0003_alter_institute_name'),
        ('student', '0002_alter_student_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='contract',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='contract'),
        ),
        migrations.AlterField(
            model_name='student',
            name='full_name',
            field=models.CharField(max_length=255, verbose_name='full name'),
        ),
        migrations.AlterField(
            model_name='student',
            name='get_status_display',
            field=models.IntegerField(choices=[(1, 'Yangi'), (2, 'Modernarsiyada'), (3, 'Tasdiqlangan'), (4, 'Bekor qilingan')], default=1, verbose_name='display status'),
        ),
        migrations.AlterField(
            model_name='student',
            name='given',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='given'),
        ),
        migrations.AlterField(
            model_name='student',
            name='institute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institute.institute', verbose_name='institute'),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(max_length=255, verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='student',
            name='type',
            field=models.IntegerField(choices=[(1, 'Bakalavr'), (2, 'Magistr'), (3, 'Phd')], verbose_name='type'),
        ),
    ]
