# Generated by Django 4.2.4 on 2023-08-30 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_student_contract_student_institute_student_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='type',
            field=models.IntegerField(choices=[('Bakalavr', 1), ('Magistr', 2), ('Phd', 3)], max_length=255),
        ),
    ]
