# Generated by Django 4.2.4 on 2023-08-30 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_alter_student_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='get_status_display',
            field=models.CharField(blank=True, default='Yangi', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='type',
            field=models.IntegerField(choices=[(1, 'Bakalavr'), (2, 'Magistr'), (3, 'Phd')], max_length=255),
        ),
    ]
