# Generated by Django 4.2.4 on 2023-08-31 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_alter_student_get_status_display'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='get_status_display',
            field=models.IntegerField(blank=True, choices=[(1, 'Yangi'), (2, 'Modernarsiyada'), (3, 'Tasdiqlangan'), (4, 'Bekor qilingan')], default=1, null=True),
        ),
    ]
