# Generated by Django 4.2.4 on 2023-09-02 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_alter_student_get_status_display'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='contract',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='given',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
